AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  pythonVersion:
    Type: String
    Default: python3.8
  lambdaLayerARN:
    Type: String
    Default: 'arn:aws:lambda:us-east-2:735029168602:layer:TravelMapLambdaLayer:26'
  apiStageName:
    Type: String
    Default: dev
Resources:
  ScrapMapAPIs:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: ScrapMapAPIs
  Auth:
    Type: 'AWS::CloudFormation::Stack'
    Properties: 
      TemplateURL: ./auth/auth.yaml
      Parameters:
        stageName: !Ref apiStageName
        rootResourceId: !GetAtt ScrapMapAPIs.RootResourceId
        restApiId: !Ref ScrapMapAPIs
        pythonVersion: !Ref pythonVersion
        lambdaLayerARN: !Ref lambdaLayerARN

