AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  pythonPath:
    Type: String
    Default: /var/task/src:/opt/lib:/opt
  pythonVersion:
    Type: String
    Default: python3.8
  lambdaLayerARN:
    Type: String
    Default: arn:aws:lambda:us-east-2:735029168602:layer:TravelMapLambdaLayer:26
  apiStageName:
    Type: String
  cognitoUserPoolId:
    Type: String
  cognitoClientId:
    Type: String
  cognitoClientSecret:
    Type: String
  dynamoTableName:
    Type: String
    Default: ScrapMapTable

Resources:
  ScrapMapDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref dynamoTableName
      AttributeDefinitions:
        -
          AttributeName: "PK"
          AttributeType: "S"
        -
          AttributeName: "SK"
          AttributeType: "S"
        # -
        #   AttributeName: "Data"
        #   AttributeType: "M"
      KeySchema:
        -
          AttributeName: "PK"
          KeyType: "HASH"
        -
          AttributeName: "SK"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
  ScrapMapAPIs:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: ScrapMapAPIs
  Auth:
    Type: 'AWS::CloudFormation::Stack'
    Properties: 
      TemplateURL: ./auth/auth.yaml
      Parameters:
        apiStageName: !Ref apiStageName
        rootResourceId: !GetAtt ScrapMapAPIs.RootResourceId
        restApiId: !Ref ScrapMapAPIs
        pythonPath: !Ref pythonPath
        pythonVersion: !Ref pythonVersion
        lambdaLayerARN: !Ref lambdaLayerARN
        cognitoUserPoolId: !Ref cognitoUserPoolId
        cognitoClientId: !Ref cognitoClientId
        cognitoClientSecret: !Ref cognitoClientSecret
  API:
    Type: 'AWS::CloudFormation::Stack'
    Properties: 
      TemplateURL: ./api/api.yaml
      Parameters:
        apiStageName: !Ref apiStageName
        rootResourceId: !GetAtt ScrapMapAPIs.RootResourceId
        restApiId: !Ref ScrapMapAPIs
        pythonPath: !Ref pythonPath
        pythonVersion: !Ref pythonVersion
        dynamoTableArn: !GetAtt ScrapMapDynamoTable.Arn
        dynamoTableName: !Ref dynamoTableName

