# Generated by Django 3.0.1 on 2020-01-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
