# Generated by Django 3.0.1 on 2020-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200106_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimages',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
