# Generated by Django 3.0.1 on 2020-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_placeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='BOOF', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='CHORK', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='number',
            field=models.CharField(default='PISS', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.CharField(default='SUCK', max_length=80),
            preserve_default=False,
        ),
    ]
