# Generated by Django 3.0.1 on 2020-03-04 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='number',
        ),
        migrations.RemoveField(
            model_name='place',
            name='street',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='324 sdfdsf', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.CharField(default='Boof, Chork', max_length=500),
            preserve_default=False,
        ),
    ]
