# Generated by Django 3.0.1 on 2020-03-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_place_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
