# Generated by Django 3.0.1 on 2020-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200401_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='main_type',
            field=models.CharField(default='establishment', max_length=100),
        ),
    ]
