# Generated by Django 3.0.1 on 2020-04-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_place_main_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
