AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ""

Parameters:
  apiGatewayStageName:
    Type: String
  rootResourceId:
    Type: String
  restApiId:
    Type: String
  pythonVersion:
    Type: String
  lambdaLayerARN:
    Type: String

Resources:
  ### /auth ###
  AuthResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref restApiId
      ParentId: !Ref rootResourceId
      PathPart: auth
