AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ""

Parameters:
  pythonPath:
    Type: String
  pythonVersion:
    Type: String
  apiStageName:
    Type: String
  rootResourceId:
    Type: String
  restApiId:
    Type: String
  dynamoTableArn:
    Type: String
  dynamoTableName:
    Type: String

Resources:
  ### /api Resource ###
  APIResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref restApiId
      ParentId: !Ref rootResourceId
      PathPart: api

  # Write Only role for Dynamo
  LambdaDynamoWriteOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:BatchWrite"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "*"

  # Read Only role for Dynamo
  LambdaDynamoReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:ConditionCheckItem"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "*"

  ### GET /api/destinations ###
  DestinationsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref restApiId
      ParentId: !Ref APIResource
      PathPart: destinations
  
  DestinationsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt DestinationsGetFunction.Arn
      ResourceId: !Ref DestinationsResource
      RestApiId: !Ref restApiId

  DestinationsGetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./destinations/get/
      Description: "A function for retrieving a user's Destinations"
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaDynamoReadOnlyRole.Arn
      Environment:
        Variables:
          PYTHONPATH: !Ref pythonPath

  DestinationsGetInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DestinationsGetFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiId}/*/GET/api/destinations"

  # /api Deployment
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - DestinationsGetMethod
    Properties:
      RestApiId: !Ref restApiId
      StageName: !Ref apiStageName