AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ""

Parameters:
  pythonPath:
    Type: String
  pythonVersion:
    Type: String
  apiStageName:
    Type: String
  rootResourceId:
    Type: String
  restApiId:
    Type: String
  dynamoTableArn:
    Type: String
  dynamoTableName:
    Type: String
  authorizerId: 
    Type: String

Resources:
  ### /api Resource ###
  APIResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref restApiId
      ParentId: !Ref rootResourceId
      PathPart: api

  # Write Only role for Dynamo
  LambdaDynamoWriteOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:BatchWrite"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "*"

  # Read Only role for Dynamo
  LambdaDynamoReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:ConditionCheckItem"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "*"

  # Delete role for Dynamo
  LambdaDynamoDeleteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:ConditionCheckItem"
                  - "dynamodb:DeleteItem"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "*"

  ### GET /api/destinations ###
  DestinationsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref restApiId
      ParentId: !Ref APIResource
      PathPart: destinations
  
  DestinationsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      RequestParameters:
        method.request.querystring.user: true
      RequestValidatorId: !Ref DestinationsRequestValidator
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt DestinationsGetFunction.Arn
      ResourceId: !Ref DestinationsResource
      RestApiId: !Ref restApiId

  DestinationsGetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./destinations/get/
      Description: "A function for retrieving a user's Destinations"
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaDynamoReadOnlyRole.Arn
      Environment:
        Variables:
          PYTHONPATH: !Ref pythonPath

  DestinationsGetInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DestinationsGetFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiId}/*/GET/api/destinations"

  DestinationsRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref restApiId
      ValidateRequestBody: true
      ValidateRequestParameters: true

  # POST /api/destinations
  DestinationsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref authorizerId
      HttpMethod: POST
      RequestValidatorId: !Ref DestinationsRequestValidator
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt DestinationsPostFunction.Arn
      ResourceId: !Ref DestinationsResource
      RestApiId: !Ref restApiId

  DestinationsPostFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./destinations/post/
      Description: "A function for retrieving a user's Destinations"
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaDynamoWriteOnlyRole.Arn
      Environment:
        Variables:
          PYTHONPATH: !Ref pythonPath
          DYNAMO_TABLE_NAME: !Ref dynamoTableName

  DestinationsPostInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DestinationsPostFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiId}/*/POST/api/destinations"

  # DELETE /api/destinations
  DestinationsDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref authorizerId
      RequestParameters:
        method.request.querystring.destination_id: true
      RequestValidatorId: !Ref DestinationsRequestValidator
      HttpMethod: DELETE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt DestinationsDeleteFunction.Arn
      ResourceId: !Ref DestinationsResource
      RestApiId: !Ref restApiId

  DestinationsDeleteFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./destinations/delete/
      Description: "A function for deleting a user's Destination"
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaDynamoDeleteRole.Arn
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: !Ref dynamoTableName
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:3


  DestinationsDeleteInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DestinationsDeleteFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiId}/*/DELETE/api/destinations"


  # /api Deployment
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - DestinationsGetMethod
      - DestinationsPostMethod
      - DestinationsDeleteMethod
    Properties:
      RestApiId: !Ref restApiId
      StageName: !Ref apiStageName